Feat/add dropdown component
ostis-ai/ostis-ui-lib pull request #12
Opened 2023-06-07 10:35 UTC by andrewKapustin22

2023-06-07 10:36 UTC, aleksgrin approved these changes

2023-06-07 11:43 UTC, ACherkas12 approved these changes

2023-06-08 10:26 UTC, Kovallevz requested changes

2023-06-08 10:26 UTC, Kovallevz commented on src/components/Dropdown/Dropdown.tsx
> +  alignSelf?: 'auto' | 'flex-start' | 'flex-end' | 'center' | 'baseline' | 'stretch';
Move to type.

2023-06-08 10:26 UTC, Kovallevz commented on src/components/Dropdown/Dropdown.tsx
> +      // TODO: Добавить проверку, если элемент слишком большой и не помещается ни сверху ни снизу
Translate into English.

2023-06-08 10:26 UTC, Kovallevz commented on src/components/Dropdown/styled.ts
> +    }};
Make a separation of styles.

2023-06-08 10:26 UTC, Kovallevz commented on src/components/Dropdown/styled.ts
> +  flex: 0 0 auto;
Make a separation of styles.

2023-06-08 10:26 UTC, Kovallevz commented on src/components/Dropdown/styled.ts
> +  }
Make a separation of styles.

2023-06-08 10:26 UTC, Kovallevz commented on src/components/DropdownOption/styled.ts
> +  cursor: pointer;
Make a separation of styles.

2023-06-08 13:04 UTC, merged